version: '2.1'

services:
  proxy:
    build:
      context: ./nginx_proxy
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - django_api
      - polymer

  django_api:
    env_file:
      - django_api/.env
    build:
      context: ./django_api
      dockerfile: ./Dockerfile-dev
      args:
        ENV: dev
        REQUIREMENT_FILE: dev.txt
    command: bash -c "/usr/local/bin/waitforit -host=db -port=5432 && python /code/django_api/manage.py migrate && uwsgi --ini /code/django_api/uwsgi.ini"
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
#    volumes:
#      - './postgres_data:/var/lib/postgresql/data'

  polymer:
    build:
      context: ./polymer
      dockerfile: ./Dockerfile-dev
    command: ash -c "polymer serve -H 0.0.0.0"
