version: '2.1'

services:
  proxy:
    image: unicef/etools-prp-nginx-proxy
    build:
      context: ./nginx_proxy
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - django_api
      - polymer

  django_api:
    image: unicef/etools-prp-django-api
    env_file:
      - django_api/.env
    build:
      context: ./django_api
      dockerfile: ./Dockerfile
      args:
        ENV: dev
        REQUIREMENT_FILE: dev.txt
    volumes:
      - './django_api:/code/'
    command: bash -c "/usr/local/bin/waitforit -host=db -port=5432 && python /code/manage.py migrate && python manage.py collectstatic --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: unicef/etools-prp-db
    build:
      context: ./db
      dockerfile: ./Dockerfile
#    volumes:
#      - './postgres_data:/var/lib/postgresql/data'

  polymer:
    image: unicef/etools-prp-polymer
    build:
      context: ./polymer
      dockerfile: ./Dockerfile
    volumes:
        - ./polymer/:/code
        - /code/node_modules
        - /code/bower_components
    command: ash -c "npm run dev"
