version: '2.1'

services:
beater-prp:
  command: python manage.py celery beat --loglevel=debug
  image: 'unicef/etools-prp:develop'
  env_file:
    - .env
  restart: always
 
celerycam-prp:
  autoredeploy: true
  command: python manage.py celerycam
  image: 'unicef/etools-prp:develop'
  env_file:
    - .env
  restart: always

flower-prp:
  command: 'flower --address=0.0.0.0 --port=8080 --broker=redis://prp-redis:6379/0 -l DEBUG --auto_refresh=False --debug=True --autoreload=False --url_prefix=flower'
  expose:
    - '8080'
  image: 'unicef/etools-prp:develop'
  env_file:
    - .env
  restart: always

worker-prp:
  command: python manage.py celery worker -E --loglevel=info
  image: 'unicef/etools-prp:develop'
  env_file:
    - .env
  restart: always

  proxy:
    image: unicef/etools-prp-nginx-proxy
    environment:
      - DJANGO_APPLICATION_SERVICE_HOST=django_api
    build:
      context: ./nginx_proxy
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - django_api
      - polymer

  django_api:
    image: unicef/etools-prp
    env_file:
      - .env
    build:
      context: ./django_api
      dockerfile: ./Dockerfile
      args:
        ENV: dev
        REQUIREMENT_FILE: dev.txt
    volumes:
      - './django_api:/code/'
    command: bash -c "/usr/local/bin/waitforit -host=db -port=5432 && python /code/manage.py makemigrations --merge --noinput && python /code/manage.py migrate && python manage.py collectstatic --noinput && uwsgi --ini /code/django_api/uwsgi.ini"
    depends_on:
      - db

  db:
    image: unicef/etools-prp-db
    env_file:
      - .env
    build:
      context: ./db
      dockerfile: ./Dockerfile
#    volumes:
#      - './postgres_data:/var/lib/postgresql/data'

  redis:
    image: unicef/etools-prp-redis
    build:
      context: ./redis
      dockerfile: ./Dockerfile

  polymer:
    image: unicef/etools-prp-polymer
    build:
      context: ./polymer
      dockerfile: ./Dockerfile
    volumes:
        - ./polymer/:/code
        - /code/node_modules
        - /code/bower_components
    command: ash -c "npm run dev"
