apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: beater
  labels:
    app: beater
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beater-container
  template:
    metadata:
      labels:
        app: beater-container
    spec:
      containers:
        - name: beater
          image: unicef/etools-prp
          volumeMounts:
            - name: data-volume
              mountPath: /data
          command: ["bash"]
          args: ["-c", "/usr/local/bin/waitforit -host=db -port=5432 && python manage.py celery beat --loglevel=${CELERY_LOG_LEVEL:-debug}"]
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_ALLOWED_HOST
              value: {{DJANGO_ALLOWED_HOST}}
            
            - name: DJANGO_DEBUG
              value: "{{DJANGO_DEBUG}}"

            - name: DOMAIN_NAME
              value: {{DOMAIN_NAME}}

            - name: ENV
              value: {{ENV}}

            - name: REDIS_URL
              value: redis://redis:6379/0

            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: aws-s3-access-key-id
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: aws-s3-secret-access-key
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: aws-storage-bucket-name
            - name: AZURE_B2C_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: azure-b2c-client-id
            - name: AZURE_B2C_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: azure-b2c-client-secret
            - name: AZURE_B2C_POLICY_NAME
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: azure-b2c-policy-name
            - name: ELASTIC_APM_DEBUG
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: elastic-apm-debug
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: elastic-apm-secret-token
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: elastic-apm-server-url
            - name: ELASTIC_APM_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: elastic-apm-service-name
            - name: EMAIL_BACKEND
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: email-backend
            
            - name: PMP_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: pmp-api-password
            - name: PMP_API_USER
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: pmp-api-user
            
            # - name: POSTGRES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: eprp-staging
            #       key: postgres-password

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: secret-key
      volumes:
      - name: static-volume-{{NAMESPACE}}
        persistentVolumeClaim:
          claimName: static-volume-claim-{{NAMESPACE}}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-container
  template:
    metadata:
      labels:
        app: worker-container
    spec:
      containers:
        - name: beater
          image: unicef/etools-prp
          volumeMounts:
            - name: data-volume
              mountPath: /data
          command: ["bash"]
          args: ["-c", "/usr/local/bin/waitforit -host=db -port=5432 && python manage.py celery worker -E --loglevel=${CELERY_LOG_LEVEL:-info}"]
          ports:
            - containerPort: 8000
          env:
            - name: C_FORCE_ROOT
              value: "1"

            - name: DJANGO_ALLOWED_HOST
              value: {{DJANGO_ALLOWED_HOST}}
            
            - name: DJANGO_DEBUG
              value: "{{DJANGO_DEBUG}}"

            - name: DOMAIN_NAME
              value: {{DOMAIN_NAME}}

            - name: ENV
              value: {{ENV}}

            - name: REDIS_URL
              value: redis://redis:6379/0

            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: aws-s3-access-key-id
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: aws-s3-secret-access-key
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: aws-storage-bucket-name
            - name: AZURE_B2C_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: azure-b2c-client-id
            - name: AZURE_B2C_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: azure-b2c-client-secret
            - name: AZURE_B2C_POLICY_NAME
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: azure-b2c-policy-name
            - name: ELASTIC_APM_DEBUG
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: elastic-apm-debug
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: elastic-apm-secret-token
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: elastic-apm-server-url
            - name: ELASTIC_APM_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: elastic-apm-service-name
            - name: EMAIL_BACKEND
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: email-backend
            
            - name: PMP_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: pmp-api-password
            - name: PMP_API_USER
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: pmp-api-user
            
            # - name: POSTGRES_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: eprp-staging
            #       key: postgres-password
            
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: eprp-staging
                  key: secret-key
            
      volumes:
      - name: static-volume-{{NAMESPACE}}
        persistentVolumeClaim:
          claimName: static-volume-claim-{{NAMESPACE}}
