---
kind: Service
apiVersion: v1
metadata:
  name: proxy-service
spec:
  ports:
   - name: http
     protocol: TCP
     port: 80
  type: NodePort
  selector:
    app: proxy-container
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-container
  template:
    metadata:
      labels:
        app: proxy-container
    spec:
      containers:
        - name: proxy
          image: unicef/etools-prp-nginx-proxy
          volumeMounts:
            - name: data-volume
              mountPath: /data
          ports:
            - containerPort: 80
          env:
            - name: DJANGO_APPLICATION_SERVICE_HOST
              value: backend
            # - name: ADMIN_MAIL
            #   value: unicef@tivix.com
            # - name: DOMAIN_NAME
            #   value: prp.tivixlabs.com
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-volume-claim